# Generated by Django 4.0.4 on 2022-05-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentYear', models.IntegerField()),
                ('lastId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('level', models.CharField(max_length=1)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('status', models.BooleanField()),
                ('email', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=11)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.department')),
            ],
        ),
    ]
