# Generated by Django 4.0.4 on 2022-05-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_student_studid_alter_student_id_alter_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studid',
            new_name='studId',
        ),
    ]
